-- Migration ladder as RESOLVED by the release this fixture is named for — every rung's
-- SQL frozen as that era's code (including its generators) emitted it, plus the same
-- version-table DDL and stamps MigrateLockedAsync writes. Generated by tools/generate-
-- ladder-fixture; regenerate at each release cut from the release tag. DO NOT HAND-EDIT.
-- ===BATCH=== bootstrap
SET search_path = collect, config, public;
CREATE TABLE IF NOT EXISTS darling_schema_version (
    version integer NOT NULL PRIMARY KEY,
    name text NOT NULL,
    applied_at timestamp NOT NULL
);
-- ===BATCH=== V1 collector-tables
/* Darling collector tables — generated from PerformanceMonitor.Collectors definitions.
   Column names and types mirror Lite's DuckDB schema (see PgSchemaGenerator remarks). */

CREATE TABLE IF NOT EXISTS wait_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    wait_type text,
    waiting_tasks_count bigint,
    wait_time_ms bigint,
    signal_wait_time_ms bigint,
    delta_waiting_tasks bigint,
    delta_wait_time_ms bigint,
    delta_signal_wait_time_ms bigint
);
CREATE INDEX IF NOT EXISTS idx_wait_stats_time ON wait_stats(server_id, collection_time);

CREATE TABLE IF NOT EXISTS latch_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    latch_class text,
    waiting_requests_count bigint,
    wait_time_ms bigint,
    max_wait_time_ms bigint,
    delta_waiting_requests_count bigint,
    delta_wait_time_ms bigint,
    delta_max_wait_time_ms bigint
);
CREATE INDEX IF NOT EXISTS idx_latch_stats_time ON latch_stats(server_id, collection_time);

CREATE TABLE IF NOT EXISTS spinlock_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    spinlock_name text,
    collisions bigint,
    spins bigint,
    spins_per_collision double precision,
    sleep_time bigint,
    backoffs bigint,
    delta_collisions bigint,
    delta_spins bigint,
    delta_sleep_time bigint,
    delta_backoffs bigint
);
CREATE INDEX IF NOT EXISTS idx_spinlock_stats_time ON spinlock_stats(server_id, collection_time);

CREATE TABLE IF NOT EXISTS cpu_scheduler_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    max_workers_count integer,
    scheduler_count integer,
    cpu_count integer,
    total_runnable_tasks_count integer,
    total_work_queue_count bigint,
    total_current_workers_count integer,
    avg_runnable_tasks_count numeric(38,2),
    total_active_request_count integer,
    total_queued_request_count integer,
    total_blocked_task_count integer,
    total_active_parallel_thread_count bigint,
    runnable_request_count integer,
    total_request_count integer,
    runnable_percent numeric(38,2),
    worker_thread_exhaustion_warning boolean,
    runnable_tasks_warning boolean,
    blocked_tasks_warning boolean,
    queued_requests_warning boolean,
    total_physical_memory_kb bigint,
    available_physical_memory_kb bigint,
    system_memory_state_desc text,
    physical_memory_pressure_warning boolean,
    total_node_count integer,
    nodes_online_count integer,
    offline_cpu_count integer,
    offline_cpu_warning boolean
);
CREATE INDEX IF NOT EXISTS idx_cpu_scheduler_stats_time ON cpu_scheduler_stats(server_id, collection_time);

CREATE TABLE IF NOT EXISTS plan_cache_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    cacheobjtype text,
    objtype text,
    total_plans integer,
    total_size_mb integer,
    single_use_plans integer,
    single_use_size_mb integer,
    multi_use_plans integer,
    multi_use_size_mb integer,
    avg_use_count numeric(38,2),
    avg_size_kb integer,
    oldest_plan_create_time timestamp
);
CREATE INDEX IF NOT EXISTS idx_plan_cache_stats_time ON plan_cache_stats(server_id, collection_time);

CREATE TABLE IF NOT EXISTS tempdb_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    user_object_reserved_mb numeric(18,2),
    internal_object_reserved_mb numeric(18,2),
    version_store_reserved_mb numeric(18,2),
    total_reserved_mb numeric(18,2),
    unallocated_mb numeric(18,2),
    total_sessions_using_tempdb bigint,
    top_session_id integer,
    top_session_tempdb_mb numeric(18,2)
);
CREATE INDEX IF NOT EXISTS idx_tempdb_stats_time ON tempdb_stats(server_id, collection_time);

CREATE TABLE IF NOT EXISTS memory_grant_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    resource_semaphore_id smallint,
    pool_id integer,
    target_memory_mb numeric(18,2),
    max_target_memory_mb numeric(18,2),
    total_memory_mb numeric(18,2),
    available_memory_mb numeric(18,2),
    granted_memory_mb numeric(18,2),
    used_memory_mb numeric(18,2),
    grantee_count integer,
    waiter_count integer,
    timeout_error_count bigint,
    forced_grant_count bigint,
    timeout_error_count_delta bigint,
    forced_grant_count_delta bigint
);
CREATE INDEX IF NOT EXISTS idx_memory_grant_stats_time ON memory_grant_stats(server_id, collection_time);

CREATE TABLE IF NOT EXISTS cpu_utilization_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    sample_time timestamp,
    sqlserver_cpu_utilization integer,
    other_process_cpu_utilization integer
);
CREATE INDEX IF NOT EXISTS idx_cpu_utilization_stats_time ON cpu_utilization_stats(server_id, collection_time);

CREATE TABLE IF NOT EXISTS memory_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    total_physical_memory_mb numeric(18,2),
    available_physical_memory_mb numeric(18,2),
    total_page_file_mb numeric(18,2),
    available_page_file_mb numeric(18,2),
    system_memory_state text,
    sql_memory_model text,
    target_server_memory_mb numeric(18,2),
    total_server_memory_mb numeric(18,2),
    buffer_pool_mb numeric(18,2),
    plan_cache_mb numeric(18,2),
    max_workers_count integer,
    current_workers_count integer
);
CREATE INDEX IF NOT EXISTS idx_memory_stats_time ON memory_stats(server_id, collection_time);

CREATE TABLE IF NOT EXISTS memory_clerks (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    clerk_type text,
    memory_mb numeric(18,2)
);
CREATE INDEX IF NOT EXISTS idx_memory_clerks_time ON memory_clerks(server_id, collection_time);

CREATE TABLE IF NOT EXISTS memory_pressure_events (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    sample_time timestamp,
    memory_notification text,
    memory_indicators_process integer,
    memory_indicators_system integer
);
CREATE INDEX IF NOT EXISTS idx_memory_pressure_events_time ON memory_pressure_events(server_id, sample_time);

CREATE TABLE IF NOT EXISTS file_io_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    database_name text,
    file_name text,
    file_type text,
    physical_name text,
    size_mb numeric(18,2),
    num_of_reads bigint,
    num_of_writes bigint,
    read_bytes bigint,
    write_bytes bigint,
    io_stall_read_ms bigint,
    io_stall_write_ms bigint,
    io_stall_queued_read_ms bigint,
    io_stall_queued_write_ms bigint,
    delta_reads bigint,
    delta_writes bigint,
    delta_read_bytes bigint,
    delta_write_bytes bigint,
    delta_stall_read_ms bigint,
    delta_stall_write_ms bigint,
    delta_stall_queued_read_ms bigint,
    delta_stall_queued_write_ms bigint
);
CREATE INDEX IF NOT EXISTS idx_file_io_stats_time ON file_io_stats(server_id, collection_time);

CREATE TABLE IF NOT EXISTS server_properties (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    edition text,
    product_version text,
    product_level text,
    product_update_level text,
    engine_edition integer,
    cpu_count integer,
    hyperthread_ratio integer,
    physical_memory_mb bigint,
    socket_count integer,
    cores_per_socket integer,
    is_hadr_enabled boolean,
    is_clustered boolean,
    enterprise_features text,
    service_objective text,
    vcore_count integer,
    lock_pages_in_memory boolean,
    instant_file_initialization_enabled boolean,
    memory_dump_count integer,
    sqlserver_start_time timestamp,
    host_os_version text,
    ag_replica_role text,
    utc_offset_minutes integer
);
CREATE INDEX IF NOT EXISTS idx_server_properties_time ON server_properties(server_id, collection_time);

CREATE TABLE IF NOT EXISTS server_config (
    config_id bigint NOT NULL,
    capture_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    configuration_name text,
    value_configured bigint,
    value_in_use bigint,
    is_dynamic boolean,
    is_advanced boolean
);

CREATE TABLE IF NOT EXISTS database_config (
    config_id bigint NOT NULL,
    capture_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    database_name text,
    state_desc text,
    compatibility_level integer,
    collation_name text,
    recovery_model text,
    is_read_only boolean,
    is_auto_close_on boolean,
    is_auto_shrink_on boolean,
    is_auto_create_stats_on boolean,
    is_auto_update_stats_on boolean,
    is_auto_update_stats_async_on boolean,
    is_read_committed_snapshot_on boolean,
    snapshot_isolation_state text,
    is_parameterization_forced boolean,
    is_query_store_on boolean,
    is_encrypted boolean,
    is_trustworthy_on boolean,
    is_db_chaining_on boolean,
    is_broker_enabled boolean,
    is_cdc_enabled boolean,
    is_mixed_page_allocation_on boolean,
    log_reuse_wait_desc text,
    page_verify_option text,
    target_recovery_time_seconds integer,
    delayed_durability text,
    is_accelerated_database_recovery_on boolean,
    is_memory_optimized_enabled boolean,
    is_optimized_locking_on boolean
);

CREATE TABLE IF NOT EXISTS trace_flags (
    config_id bigint NOT NULL,
    capture_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    trace_flag integer,
    status boolean,
    is_global boolean,
    is_session boolean
);
CREATE INDEX IF NOT EXISTS idx_trace_flags_time ON trace_flags(server_id, capture_time);

CREATE TABLE IF NOT EXISTS database_scoped_config (
    config_id bigint NOT NULL,
    capture_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    database_name text,
    configuration_name text,
    value text,
    value_for_secondary text
);
CREATE INDEX IF NOT EXISTS idx_database_scoped_config_time ON database_scoped_config(server_id, capture_time);

CREATE TABLE IF NOT EXISTS session_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    program_name text,
    connection_count bigint,
    running_count integer,
    sleeping_count integer,
    dormant_count integer,
    total_cpu_time_ms bigint,
    total_reads bigint,
    total_writes bigint,
    total_logical_reads bigint
);
CREATE INDEX IF NOT EXISTS idx_session_stats_time ON session_stats(server_id, collection_time);

CREATE TABLE IF NOT EXISTS session_summary_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    total_sessions integer,
    running_sessions integer,
    sleeping_sessions integer,
    background_sessions integer,
    dormant_sessions integer,
    idle_sessions_over_30min integer,
    sessions_waiting_for_memory integer,
    databases_with_connections integer,
    top_application_name text,
    top_application_connections integer,
    top_host_name text,
    top_host_connections integer
);
CREATE INDEX IF NOT EXISTS idx_session_summary_stats_time ON session_summary_stats(server_id, collection_time);

CREATE TABLE IF NOT EXISTS waiting_tasks (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    session_id integer,
    wait_type text,
    wait_duration_ms bigint,
    blocking_session_id integer,
    resource_description text,
    database_name text
);
CREATE INDEX IF NOT EXISTS idx_waiting_tasks_time ON waiting_tasks(server_id, collection_time);

CREATE TABLE IF NOT EXISTS procedure_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    database_name text,
    schema_name text,
    object_name text,
    object_type text,
    cached_time timestamp,
    last_execution_time timestamp,
    execution_count bigint,
    total_worker_time bigint,
    total_elapsed_time bigint,
    total_logical_reads bigint,
    total_physical_reads bigint,
    total_logical_writes bigint,
    min_worker_time bigint,
    max_worker_time bigint,
    min_elapsed_time bigint,
    max_elapsed_time bigint,
    min_logical_reads bigint,
    max_logical_reads bigint,
    min_physical_reads bigint,
    max_physical_reads bigint,
    min_logical_writes bigint,
    max_logical_writes bigint,
    total_spills bigint,
    min_spills bigint,
    max_spills bigint,
    sql_handle text,
    plan_handle text,
    delta_execution_count bigint,
    delta_worker_time bigint,
    delta_elapsed_time bigint,
    delta_logical_reads bigint,
    delta_logical_writes bigint,
    delta_physical_reads bigint,
    delta_spills bigint,
    query_plan_xml text
);
CREATE INDEX IF NOT EXISTS idx_procedure_stats_time ON procedure_stats(server_id, collection_time);

CREATE TABLE IF NOT EXISTS running_jobs (
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    job_name text,
    job_id text,
    job_enabled boolean,
    start_time timestamp,
    current_duration_seconds bigint,
    avg_duration_seconds bigint,
    p95_duration_seconds bigint,
    successful_run_count bigint,
    is_running_long boolean,
    percent_of_average numeric(10,1)
);
CREATE INDEX IF NOT EXISTS idx_running_jobs_time ON running_jobs(server_id, collection_time);

CREATE TABLE IF NOT EXISTS perfmon_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    object_name text,
    counter_name text,
    instance_name text,
    cntr_value bigint,
    delta_cntr_value bigint,
    sample_interval_seconds integer
);
CREATE INDEX IF NOT EXISTS idx_perfmon_stats_time ON perfmon_stats(server_id, collection_time);

CREATE TABLE IF NOT EXISTS dmv_blocking_snapshots (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    monitor_loop integer,
    event_time timestamp,
    database_name text,
    blocked_spid integer,
    blocked_ecid integer,
    blocked_last_tran_started timestamp,
    blocking_spid integer,
    blocking_ecid integer,
    blocking_last_tran_started timestamp,
    wait_time_ms bigint,
    lock_mode text,
    blocking_status text,
    contentious_object text,
    blocked_sql_text text,
    blocking_sql_text text,
    blocked_login_name text,
    blocked_host_name text,
    blocked_client_app text,
    blocking_login_name text,
    blocking_host_name text,
    blocking_client_app text
);
CREATE INDEX IF NOT EXISTS idx_dmv_blocking_snapshots_time ON dmv_blocking_snapshots(server_id, collection_time);

CREATE TABLE IF NOT EXISTS database_size_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    database_name text,
    database_id integer,
    file_id integer,
    file_type_desc text,
    file_name text,
    physical_name text,
    total_size_mb numeric(19,2),
    used_size_mb numeric(19,2),
    auto_growth_mb numeric(19,2),
    max_size_mb numeric(19,2),
    recovery_model_desc text,
    compatibility_level integer,
    state_desc text,
    volume_mount_point text,
    volume_total_mb numeric(19,2),
    volume_free_mb numeric(19,2),
    is_percent_growth boolean,
    growth_pct integer,
    vlf_count integer
);
CREATE INDEX IF NOT EXISTS idx_database_size_stats_time ON database_size_stats(server_id, collection_time);

CREATE TABLE IF NOT EXISTS index_object_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    sqlserver_start_time timestamp,
    database_name text,
    database_id integer,
    schema_name text,
    object_id integer,
    table_name text,
    index_id integer,
    index_name text,
    index_type_desc text,
    is_unique boolean,
    is_primary_key boolean,
    is_filtered boolean,
    partition_count integer,
    reserved_mb numeric(19,2),
    used_mb numeric(19,2),
    in_row_data_mb numeric(19,2),
    lob_data_mb numeric(19,2),
    row_overflow_mb numeric(19,2),
    total_rows bigint,
    user_seeks bigint,
    user_scans bigint,
    user_lookups bigint,
    user_updates bigint,
    last_user_seek timestamp,
    last_user_scan timestamp,
    last_user_lookup timestamp,
    last_user_update timestamp,
    leaf_insert_count bigint,
    leaf_update_count bigint,
    leaf_delete_count bigint,
    range_scan_count bigint,
    singleton_lookup_count bigint,
    row_lock_count bigint,
    row_lock_wait_count bigint,
    row_lock_wait_in_ms bigint,
    page_lock_count bigint,
    page_lock_wait_count bigint,
    page_lock_wait_in_ms bigint,
    index_lock_promotion_attempt_count bigint,
    index_lock_promotion_count bigint,
    page_latch_wait_count bigint,
    page_latch_wait_in_ms bigint,
    page_io_latch_wait_count bigint,
    page_io_latch_wait_in_ms bigint,
    key_columns text,
    included_columns text,
    filter_definition text,
    is_unique_constraint boolean,
    is_foreign_key boolean,
    is_foreign_key_reference boolean,
    is_disabled boolean,
    data_compression_desc text,
    optimize_for_sequential_key boolean,
    fill_factor smallint,
    is_padded boolean,
    allow_page_locks boolean,
    allow_row_locks boolean,
    is_indexed_view boolean
);
CREATE INDEX IF NOT EXISTS idx_index_object_stats_object ON index_object_stats(server_id, database_name, object_id, index_id, collection_time);

CREATE TABLE IF NOT EXISTS query_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    database_name text,
    query_hash text,
    query_plan_hash text,
    creation_time timestamp,
    last_execution_time timestamp,
    execution_count bigint,
    total_worker_time bigint,
    total_elapsed_time bigint,
    total_logical_reads bigint,
    total_logical_writes bigint,
    total_physical_reads bigint,
    total_clr_time bigint,
    total_rows bigint,
    total_spills bigint,
    min_worker_time bigint,
    max_worker_time bigint,
    min_elapsed_time bigint,
    max_elapsed_time bigint,
    min_physical_reads bigint,
    max_physical_reads bigint,
    min_rows bigint,
    max_rows bigint,
    min_dop bigint,
    max_dop bigint,
    min_grant_kb bigint,
    max_grant_kb bigint,
    min_used_grant_kb bigint,
    max_used_grant_kb bigint,
    min_ideal_grant_kb bigint,
    max_ideal_grant_kb bigint,
    min_reserved_threads bigint,
    max_reserved_threads bigint,
    min_used_threads bigint,
    max_used_threads bigint,
    min_spills bigint,
    max_spills bigint,
    query_text text,
    query_plan_xml text,
    sql_handle text,
    plan_handle text,
    delta_execution_count bigint,
    delta_worker_time bigint,
    delta_elapsed_time bigint,
    delta_logical_reads bigint,
    delta_logical_writes bigint,
    delta_physical_reads bigint,
    delta_rows bigint,
    delta_spills bigint,
    plan_generation_num bigint,
    sample_interval_seconds integer
);
CREATE INDEX IF NOT EXISTS idx_query_stats_time ON query_stats(server_id, collection_time);

CREATE TABLE IF NOT EXISTS query_snapshots (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    session_id integer,
    database_name text,
    elapsed_time_formatted text,
    query_text text,
    query_plan text,
    live_query_plan text,
    status text,
    blocking_session_id integer,
    wait_type text,
    wait_time_ms bigint,
    wait_resource text,
    cpu_time_ms bigint,
    total_elapsed_time_ms bigint,
    reads bigint,
    writes bigint,
    logical_reads bigint,
    granted_query_memory_gb numeric(18,2),
    transaction_isolation_level text,
    dop integer,
    parallel_worker_count integer,
    login_name text,
    host_name text,
    program_name text,
    open_transaction_count integer,
    percent_complete numeric(5,2),
    is_cdc_capture boolean,
    query_hash text,
    requested_memory_mb double precision,
    used_memory_mb double precision,
    max_used_memory_mb double precision,
    tempdb_current_mb double precision,
    tempdb_allocations_mb double precision,
    tran_log_used_mb double precision,
    tran_start_time timestamp,
    request_id integer
);
CREATE INDEX IF NOT EXISTS idx_query_snapshots_time ON query_snapshots(server_id, collection_time);

CREATE TABLE IF NOT EXISTS query_store_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    database_name text,
    query_id bigint,
    plan_id bigint,
    execution_type_desc text,
    first_execution_time timestamp,
    last_execution_time timestamp,
    module_name text,
    query_text text,
    query_hash text,
    execution_count bigint,
    avg_duration_us bigint,
    min_duration_us bigint,
    max_duration_us bigint,
    avg_cpu_time_us bigint,
    min_cpu_time_us bigint,
    max_cpu_time_us bigint,
    avg_logical_io_reads bigint,
    min_logical_io_reads bigint,
    max_logical_io_reads bigint,
    avg_logical_io_writes bigint,
    min_logical_io_writes bigint,
    max_logical_io_writes bigint,
    avg_physical_io_reads bigint,
    min_physical_io_reads bigint,
    max_physical_io_reads bigint,
    avg_clr_time_us bigint,
    min_clr_time_us bigint,
    max_clr_time_us bigint,
    min_dop bigint,
    max_dop bigint,
    avg_query_max_used_memory bigint,
    min_query_max_used_memory bigint,
    max_query_max_used_memory bigint,
    avg_rowcount bigint,
    min_rowcount bigint,
    max_rowcount bigint,
    avg_num_physical_io_reads bigint,
    min_num_physical_io_reads bigint,
    max_num_physical_io_reads bigint,
    avg_log_bytes_used bigint,
    min_log_bytes_used bigint,
    max_log_bytes_used bigint,
    avg_tempdb_space_used bigint,
    min_tempdb_space_used bigint,
    max_tempdb_space_used bigint,
    plan_type text,
    plan_forcing_type text,
    is_forced_plan boolean,
    force_failure_count bigint,
    last_force_failure_reason text,
    compatibility_level integer,
    query_plan_text text,
    query_plan_hash text,
    replica_role text
);
CREATE INDEX IF NOT EXISTS idx_query_store_stats_time ON query_store_stats(server_id, collection_time);

CREATE TABLE IF NOT EXISTS deadlocks (
    deadlock_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    deadlock_time timestamp,
    victim_process_id text,
    victim_sql_text text,
    deadlock_graph_xml text,
    victim_query_plan_xml text,
    database_name text
);
CREATE INDEX IF NOT EXISTS idx_deadlocks_time ON deadlocks(server_id, collection_time);

CREATE TABLE IF NOT EXISTS blocked_process_reports (
    blocked_report_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    event_time timestamp,
    database_name text,
    blocked_spid integer,
    blocked_ecid integer,
    blocking_spid integer,
    blocking_ecid integer,
    wait_time_ms bigint,
    wait_resource text,
    lock_mode text,
    blocked_status text,
    blocked_isolation_level text,
    blocked_log_used bigint,
    blocked_transaction_count integer,
    blocked_client_app text,
    blocked_host_name text,
    blocked_login_name text,
    blocked_sql_text text,
    blocking_status text,
    blocking_isolation_level text,
    blocking_client_app text,
    blocking_host_name text,
    blocking_login_name text,
    blocking_sql_text text,
    blocked_transaction_name text,
    blocking_transaction_name text,
    blocked_last_tran_started timestamp,
    blocking_last_tran_started timestamp,
    blocked_last_batch_started timestamp,
    blocking_last_batch_started timestamp,
    blocked_last_batch_completed timestamp,
    blocking_last_batch_completed timestamp,
    blocked_priority integer,
    blocking_priority integer,
    blocked_process_report_xml text,
    object_id integer,
    database_id integer,
    contentious_object text,
    monitor_loop integer,
    blocked_query_plan_xml text,
    blocking_query_plan_xml text
);
CREATE INDEX IF NOT EXISTS idx_blocked_process_reports_time ON blocked_process_reports(server_id, collection_time);

CREATE TABLE IF NOT EXISTS long_query_completions (
    long_query_completion_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    event_time timestamp,
    event_type text,
    database_id integer,
    database_name text,
    session_id integer,
    client_app_name text,
    client_pid integer,
    nt_username text,
    server_principal_name text,
    query_hash text,
    event_sequence bigint,
    duration_microseconds bigint,
    cpu_time_microseconds bigint,
    physical_reads bigint,
    logical_reads bigint,
    writes bigint,
    row_count bigint,
    result text,
    statement_text text,
    object_name text
);
CREATE INDEX IF NOT EXISTS idx_long_query_completions_time ON long_query_completions(server_id, collection_time);

CREATE TABLE IF NOT EXISTS system_health_events (
    system_health_event_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    event_time timestamp,
    event_type text,
    event_xml text
);
CREATE INDEX IF NOT EXISTS idx_system_health_events_time ON system_health_events(server_id, collection_time);

CREATE TABLE IF NOT EXISTS default_trace_events (
    default_trace_event_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    event_time timestamp,
    event_name text,
    event_class integer,
    spid integer,
    database_name text,
    database_id integer,
    login_name text,
    host_name text,
    application_name text,
    object_name text,
    filename text,
    integer_data bigint,
    integer_data_2 bigint,
    text_data text,
    session_login_name text,
    error_number integer,
    severity integer,
    state integer,
    event_sequence bigint,
    duration_us bigint,
    end_time timestamp
);
CREATE INDEX IF NOT EXISTS idx_default_trace_events_time ON default_trace_events(server_id, collection_time);

CREATE TABLE IF NOT EXISTS job_history (
    job_history_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    instance_id bigint,
    job_id text,
    job_name text,
    job_enabled boolean,
    category_name text,
    step_id integer,
    step_name text,
    run_status integer,
    run_status_desc text,
    run_datetime timestamp,
    run_duration_seconds bigint,
    retries_attempted integer,
    message text
);
CREATE INDEX IF NOT EXISTS idx_job_history_time ON job_history(server_id, collection_time);

CREATE TABLE IF NOT EXISTS agent_status (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    agent_running boolean,
    agent_status_desc text,
    agent_startup_desc text,
    next_scheduled_run timestamp
);
CREATE INDEX IF NOT EXISTS idx_agent_status_time ON agent_status(server_id, collection_time);

CREATE TABLE IF NOT EXISTS ag_replica_states (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    ag_name text,
    replica_server_name text,
    role_desc text,
    operational_state_desc text,
    connected_state_desc text,
    recovery_health_desc text,
    synchronization_health_desc text,
    availability_mode_desc text,
    failover_mode_desc text,
    endpoint_url text,
    is_local boolean
);
CREATE INDEX IF NOT EXISTS idx_ag_replica_states_time ON ag_replica_states(server_id, collection_time);

CREATE TABLE IF NOT EXISTS ag_database_replica_states (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    ag_name text,
    database_name text,
    replica_server_name text,
    is_local boolean,
    synchronization_state_desc text,
    last_hardened_lsn text,
    last_commit_lsn text,
    log_send_queue_size bigint,
    redo_queue_size bigint,
    log_send_rate bigint,
    redo_rate bigint,
    is_suspended boolean,
    suspend_reason_desc text,
    availability_mode_desc text,
    secondary_lag_seconds bigint,
    last_commit_time timestamp,
    last_hardened_time timestamp,
    last_redone_time timestamp,
    last_received_time timestamp,
    est_redo_completion_time_min double precision,
    est_send_drain_time_min double precision
);
CREATE INDEX IF NOT EXISTS idx_ag_database_replica_states_time ON ag_database_replica_states(server_id, collection_time);
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (1, 'collector-tables', now()::timestamp);
-- ===BATCH=== V2 server-registry-and-collection-log

CREATE TABLE IF NOT EXISTS servers (
    server_id integer NOT NULL PRIMARY KEY,
    server_name text NOT NULL,
    display_name text,
    is_enabled boolean NOT NULL DEFAULT TRUE,
    sql_engine_edition integer,
    sql_major_version integer,
    created_date timestamp,
    modified_date timestamp
);

CREATE TABLE IF NOT EXISTS collection_log (
    log_id bigint NOT NULL,
    server_id integer NOT NULL,
    server_name text,
    collector_name text NOT NULL,
    collection_time timestamp NOT NULL,
    duration_ms integer,
    status text NOT NULL,
    error_message text,
    rows_collected integer,
    sql_duration_ms integer,
    duckdb_duration_ms integer
);

CREATE INDEX IF NOT EXISTS idx_collection_log_time ON collection_log(server_id, collection_time);
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (2, 'server-registry-and-collection-log', now()::timestamp);
-- ===BATCH=== V3 alerting-stores

CREATE TABLE IF NOT EXISTS config_alert_log (
    alert_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    metric_name text NOT NULL,
    current_value double precision NOT NULL,
    threshold_value double precision NOT NULL,
    alert_sent boolean NOT NULL DEFAULT FALSE,
    notification_type text NOT NULL DEFAULT 'tray',
    send_error text,
    dismissed boolean NOT NULL DEFAULT FALSE,
    muted boolean NOT NULL DEFAULT FALSE,
    detail_text text,
    context_json text
);

CREATE INDEX IF NOT EXISTS idx_config_alert_log_time ON config_alert_log(server_id, metric_name, alert_time);

CREATE TABLE IF NOT EXISTS config_edge_trigger_watermarks (
    server_id integer NOT NULL,
    metric_name text NOT NULL,
    watermark integer NOT NULL,
    watermark_time timestamp,
    updated_at timestamp NOT NULL,
    PRIMARY KEY (server_id, metric_name)
);

CREATE TABLE IF NOT EXISTS config_mute_rules (
    id text NOT NULL PRIMARY KEY,
    enabled boolean NOT NULL DEFAULT TRUE,
    created_at_utc timestamp NOT NULL,
    expires_at_utc timestamp,
    reason text,
    server_name text,
    metric_name text,
    database_pattern text,
    query_text_pattern text,
    wait_type_pattern text,
    job_name_pattern text
);
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (3, 'alerting-stores', now()::timestamp);
-- ===BATCH=== V4 analysis-tables

CREATE TABLE IF NOT EXISTS analysis_findings (
    finding_id bigint NOT NULL,
    analysis_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    database_name text,
    time_range_start timestamp,
    time_range_end timestamp,
    severity double precision NOT NULL,
    confidence double precision NOT NULL,
    category text NOT NULL,
    story_path text NOT NULL,
    story_path_hash text NOT NULL,
    story_text text NOT NULL,
    root_fact_key text NOT NULL,
    root_fact_value double precision,
    leaf_fact_key text,
    leaf_fact_value double precision,
    fact_count integer NOT NULL,
    incident_id text,
    remediation_action_json text
);

CREATE INDEX IF NOT EXISTS idx_analysis_findings_time ON analysis_findings(server_id, analysis_time);
CREATE INDEX IF NOT EXISTS idx_analysis_findings_hash ON analysis_findings(story_path_hash);

CREATE TABLE IF NOT EXISTS analysis_muted (
    mute_id bigint NOT NULL PRIMARY KEY,
    server_id integer,
    database_name text,
    story_path_hash text NOT NULL,
    story_path text NOT NULL,
    muted_date timestamp NOT NULL,
    reason text
);

CREATE INDEX IF NOT EXISTS idx_analysis_muted_hash ON analysis_muted(story_path_hash);

CREATE OR REPLACE VIEW v_wait_stats AS SELECT * FROM wait_stats;
CREATE OR REPLACE VIEW v_query_stats AS SELECT * FROM query_stats;
CREATE OR REPLACE VIEW v_query_store_stats AS SELECT * FROM query_store_stats;
CREATE OR REPLACE VIEW v_cpu_utilization_stats AS SELECT * FROM cpu_utilization_stats;
CREATE OR REPLACE VIEW v_memory_grant_stats AS SELECT * FROM memory_grant_stats;
CREATE OR REPLACE VIEW v_memory_stats AS SELECT * FROM memory_stats;
CREATE OR REPLACE VIEW v_perfmon_stats AS SELECT * FROM perfmon_stats;
CREATE OR REPLACE VIEW v_session_stats AS SELECT * FROM session_stats;
CREATE OR REPLACE VIEW v_file_io_stats AS SELECT * FROM file_io_stats;
CREATE OR REPLACE VIEW v_blocked_process_reports AS SELECT * FROM blocked_process_reports;
CREATE OR REPLACE VIEW v_deadlocks AS SELECT * FROM deadlocks;
CREATE OR REPLACE VIEW v_dmv_blocking_snapshots AS SELECT * FROM dmv_blocking_snapshots;
CREATE OR REPLACE VIEW v_index_object_stats AS SELECT * FROM index_object_stats;
CREATE OR REPLACE VIEW v_database_size_stats AS SELECT * FROM database_size_stats;
CREATE OR REPLACE VIEW v_tempdb_stats AS SELECT * FROM tempdb_stats;
CREATE OR REPLACE VIEW v_query_snapshots AS SELECT * FROM query_snapshots;
CREATE OR REPLACE VIEW v_database_config AS SELECT * FROM database_config;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (4, 'analysis-tables', now()::timestamp);
-- ===BATCH=== V5 viewer-passthrough-views

CREATE OR REPLACE VIEW v_running_jobs AS SELECT * FROM running_jobs;
CREATE OR REPLACE VIEW v_server_config AS SELECT * FROM server_config;
CREATE OR REPLACE VIEW v_database_scoped_config AS SELECT * FROM database_scoped_config;
CREATE OR REPLACE VIEW v_trace_flags AS SELECT * FROM trace_flags;
CREATE OR REPLACE VIEW v_collection_log AS SELECT * FROM collection_log;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (5, 'viewer-passthrough-views', now()::timestamp);
-- ===BATCH=== V6 memory-tab-passthrough-views

CREATE OR REPLACE VIEW v_memory_clerks AS SELECT * FROM memory_clerks;
CREATE OR REPLACE VIEW v_memory_pressure_events AS SELECT * FROM memory_pressure_events;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (6, 'memory-tab-passthrough-views', now()::timestamp);
-- ===BATCH=== V7 viewer-plan-capture-columns

ALTER TABLE procedure_stats ADD COLUMN IF NOT EXISTS query_plan_xml text;
ALTER TABLE blocked_process_reports ADD COLUMN IF NOT EXISTS blocked_query_plan_xml text;
ALTER TABLE blocked_process_reports ADD COLUMN IF NOT EXISTS blocking_query_plan_xml text;
ALTER TABLE deadlocks ADD COLUMN IF NOT EXISTS victim_query_plan_xml text;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (7, 'viewer-plan-capture-columns', now()::timestamp);
-- ===BATCH=== V8 schema-split-collect-config
/* V8: split public into collect/config (Darling security hardening, #1262).
   Table NAMES are unchanged; search_path = collect, config, public resolves the bare
   references every SQL site already uses, so no query is re-qualified. */

CREATE SCHEMA IF NOT EXISTS collect AUTHORIZATION darling;
CREATE SCHEMA IF NOT EXISTS config AUTHORIZATION darling;

/* collect: all collector tables (from the catalog) + registry/metadata + the V4-V6 views */
ALTER TABLE IF EXISTS public.wait_stats SET SCHEMA collect;
ALTER TABLE IF EXISTS public.latch_stats SET SCHEMA collect;
ALTER TABLE IF EXISTS public.spinlock_stats SET SCHEMA collect;
ALTER TABLE IF EXISTS public.cpu_scheduler_stats SET SCHEMA collect;
ALTER TABLE IF EXISTS public.plan_cache_stats SET SCHEMA collect;
ALTER TABLE IF EXISTS public.tempdb_stats SET SCHEMA collect;
ALTER TABLE IF EXISTS public.memory_grant_stats SET SCHEMA collect;
ALTER TABLE IF EXISTS public.cpu_utilization_stats SET SCHEMA collect;
ALTER TABLE IF EXISTS public.memory_stats SET SCHEMA collect;
ALTER TABLE IF EXISTS public.memory_clerks SET SCHEMA collect;
ALTER TABLE IF EXISTS public.memory_pressure_events SET SCHEMA collect;
ALTER TABLE IF EXISTS public.file_io_stats SET SCHEMA collect;
ALTER TABLE IF EXISTS public.server_properties SET SCHEMA collect;
ALTER TABLE IF EXISTS public.server_config SET SCHEMA collect;
ALTER TABLE IF EXISTS public.database_config SET SCHEMA collect;
ALTER TABLE IF EXISTS public.trace_flags SET SCHEMA collect;
ALTER TABLE IF EXISTS public.database_scoped_config SET SCHEMA collect;
ALTER TABLE IF EXISTS public.session_stats SET SCHEMA collect;
ALTER TABLE IF EXISTS public.session_summary_stats SET SCHEMA collect;
ALTER TABLE IF EXISTS public.waiting_tasks SET SCHEMA collect;
ALTER TABLE IF EXISTS public.procedure_stats SET SCHEMA collect;
ALTER TABLE IF EXISTS public.running_jobs SET SCHEMA collect;
ALTER TABLE IF EXISTS public.perfmon_stats SET SCHEMA collect;
ALTER TABLE IF EXISTS public.dmv_blocking_snapshots SET SCHEMA collect;
ALTER TABLE IF EXISTS public.database_size_stats SET SCHEMA collect;
ALTER TABLE IF EXISTS public.index_object_stats SET SCHEMA collect;
ALTER TABLE IF EXISTS public.query_stats SET SCHEMA collect;
ALTER TABLE IF EXISTS public.query_snapshots SET SCHEMA collect;
ALTER TABLE IF EXISTS public.query_store_stats SET SCHEMA collect;
ALTER TABLE IF EXISTS public.deadlocks SET SCHEMA collect;
ALTER TABLE IF EXISTS public.blocked_process_reports SET SCHEMA collect;
ALTER TABLE IF EXISTS public.long_query_completions SET SCHEMA collect;
ALTER TABLE IF EXISTS public.system_health_events SET SCHEMA collect;
ALTER TABLE IF EXISTS public.default_trace_events SET SCHEMA collect;
ALTER TABLE IF EXISTS public.job_history SET SCHEMA collect;
ALTER TABLE IF EXISTS public.agent_status SET SCHEMA collect;
ALTER TABLE IF EXISTS public.ag_replica_states SET SCHEMA collect;
ALTER TABLE IF EXISTS public.ag_database_replica_states SET SCHEMA collect;
ALTER TABLE IF EXISTS public.servers SET SCHEMA collect;
ALTER TABLE IF EXISTS public.collection_log SET SCHEMA collect;
ALTER TABLE IF EXISTS public.analysis_findings SET SCHEMA collect;
ALTER TABLE IF EXISTS public.darling_schema_version SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_wait_stats SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_query_stats SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_query_store_stats SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_cpu_utilization_stats SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_memory_grant_stats SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_memory_stats SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_perfmon_stats SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_session_stats SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_file_io_stats SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_blocked_process_reports SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_deadlocks SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_dmv_blocking_snapshots SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_index_object_stats SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_database_size_stats SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_tempdb_stats SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_query_snapshots SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_database_config SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_running_jobs SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_server_config SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_database_scoped_config SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_trace_flags SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_collection_log SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_memory_clerks SET SCHEMA collect;
ALTER VIEW IF EXISTS public.v_memory_pressure_events SET SCHEMA collect;

/* config: the operator-writable coordination + analysis-mute tables */
ALTER TABLE IF EXISTS public.config_alert_log SET SCHEMA config;
ALTER TABLE IF EXISTS public.config_edge_trigger_watermarks SET SCHEMA config;
ALTER TABLE IF EXISTS public.config_mute_rules SET SCHEMA config;
ALTER TABLE IF EXISTS public.analysis_muted SET SCHEMA config;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (8, 'schema-split-collect-config', now()::timestamp);
-- ===BATCH=== V9 server-inventory-cost-fields

ALTER TABLE server_properties ADD COLUMN IF NOT EXISTS sqlserver_start_time timestamp;
ALTER TABLE server_properties ADD COLUMN IF NOT EXISTS host_os_version text;
ALTER TABLE server_properties ADD COLUMN IF NOT EXISTS ag_replica_role text;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS monthly_cost_usd numeric;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (9, 'server-inventory-cost-fields', now()::timestamp);
-- ===BATCH=== V10 latch-spinlock-collectors
/* V10: latch_stats + spinlock_stats collectors (Dashboard->Darling parity, #1262).
   Generated from the collector definitions so the tables match the fresh V1 shape. */

CREATE TABLE IF NOT EXISTS latch_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    latch_class text,
    waiting_requests_count bigint,
    wait_time_ms bigint,
    max_wait_time_ms bigint,
    delta_waiting_requests_count bigint,
    delta_wait_time_ms bigint,
    delta_max_wait_time_ms bigint
);
CREATE INDEX IF NOT EXISTS idx_latch_stats_time ON latch_stats(server_id, collection_time);
CREATE OR REPLACE VIEW v_latch_stats AS SELECT * FROM latch_stats;

CREATE TABLE IF NOT EXISTS spinlock_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    spinlock_name text,
    collisions bigint,
    spins bigint,
    spins_per_collision double precision,
    sleep_time bigint,
    backoffs bigint,
    delta_collisions bigint,
    delta_spins bigint,
    delta_sleep_time bigint,
    delta_backoffs bigint
);
CREATE INDEX IF NOT EXISTS idx_spinlock_stats_time ON spinlock_stats(server_id, collection_time);
CREATE OR REPLACE VIEW v_spinlock_stats AS SELECT * FROM spinlock_stats;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (10, 'latch-spinlock-collectors', now()::timestamp);
-- ===BATCH=== V11 cpu-scheduler-plan-cache-collectors
/* V11: cpu_scheduler_stats + plan_cache_stats collectors (Dashboard->Darling parity, #1262).
   Generated from the collector definitions so the tables match the fresh V1 shape. */

CREATE TABLE IF NOT EXISTS cpu_scheduler_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    max_workers_count integer,
    scheduler_count integer,
    cpu_count integer,
    total_runnable_tasks_count integer,
    total_work_queue_count bigint,
    total_current_workers_count integer,
    avg_runnable_tasks_count numeric(38,2),
    total_active_request_count integer,
    total_queued_request_count integer,
    total_blocked_task_count integer,
    total_active_parallel_thread_count bigint,
    runnable_request_count integer,
    total_request_count integer,
    runnable_percent numeric(38,2),
    worker_thread_exhaustion_warning boolean,
    runnable_tasks_warning boolean,
    blocked_tasks_warning boolean,
    queued_requests_warning boolean,
    total_physical_memory_kb bigint,
    available_physical_memory_kb bigint,
    system_memory_state_desc text,
    physical_memory_pressure_warning boolean,
    total_node_count integer,
    nodes_online_count integer,
    offline_cpu_count integer,
    offline_cpu_warning boolean
);
CREATE INDEX IF NOT EXISTS idx_cpu_scheduler_stats_time ON cpu_scheduler_stats(server_id, collection_time);
CREATE OR REPLACE VIEW v_cpu_scheduler_stats AS SELECT * FROM cpu_scheduler_stats;

CREATE TABLE IF NOT EXISTS plan_cache_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    cacheobjtype text,
    objtype text,
    total_plans integer,
    total_size_mb integer,
    single_use_plans integer,
    single_use_size_mb integer,
    multi_use_plans integer,
    multi_use_size_mb integer,
    avg_use_count numeric(38,2),
    avg_size_kb integer,
    oldest_plan_create_time timestamp
);
CREATE INDEX IF NOT EXISTS idx_plan_cache_stats_time ON plan_cache_stats(server_id, collection_time);
CREATE OR REPLACE VIEW v_plan_cache_stats AS SELECT * FROM plan_cache_stats;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (11, 'cpu-scheduler-plan-cache-collectors', now()::timestamp);
-- ===BATCH=== V12 session-summary-collector
/* V12: session_summary_stats collector (Dashboard->Darling connection-leak / idle parity, #1262).
   Generated from the collector definition so the table matches the fresh V1 shape. */

CREATE TABLE IF NOT EXISTS session_summary_stats (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    total_sessions integer,
    running_sessions integer,
    sleeping_sessions integer,
    background_sessions integer,
    dormant_sessions integer,
    idle_sessions_over_30min integer,
    sessions_waiting_for_memory integer,
    databases_with_connections integer,
    top_application_name text,
    top_application_connections integer,
    top_host_name text,
    top_host_connections integer
);
CREATE INDEX IF NOT EXISTS idx_session_summary_stats_time ON session_summary_stats(server_id, collection_time);
CREATE OR REPLACE VIEW v_session_summary_stats AS SELECT * FROM session_summary_stats;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (12, 'session-summary-collector', now()::timestamp);
-- ===BATCH=== V13 system-health-events-collector
/* V13: system_health_events collector (Dashboard->Darling health-parser capture parity, #1262).
   Generated from the collector definition so the table matches the fresh V1 shape. */

CREATE TABLE IF NOT EXISTS system_health_events (
    system_health_event_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    event_time timestamp,
    event_type text,
    event_xml text
);
CREATE INDEX IF NOT EXISTS idx_system_health_events_time ON system_health_events(server_id, collection_time);
CREATE OR REPLACE VIEW v_system_health_events AS SELECT * FROM system_health_events;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (13, 'system-health-events-collector', now()::timestamp);
-- ===BATCH=== V14 refresh-passthrough-views
/* V14: refresh every v_* passthrough view's pinned SELECT * column list (#1262).
   Postgres freezes SELECT * at CREATE, so an upgraded store's views omit columns
   ADDed later (V7 plan columns, V9 inventory); CREATE OR REPLACE re-expands them.
   Append-only ADD COLUMNs => the refresh only adds columns at the end (always legal). */

CREATE OR REPLACE VIEW v_wait_stats AS SELECT * FROM wait_stats;
CREATE OR REPLACE VIEW v_query_store_stats AS SELECT * FROM query_store_stats;
CREATE OR REPLACE VIEW v_cpu_utilization_stats AS SELECT * FROM cpu_utilization_stats;
CREATE OR REPLACE VIEW v_memory_grant_stats AS SELECT * FROM memory_grant_stats;
CREATE OR REPLACE VIEW v_memory_stats AS SELECT * FROM memory_stats;
CREATE OR REPLACE VIEW v_perfmon_stats AS SELECT * FROM perfmon_stats;
CREATE OR REPLACE VIEW v_session_stats AS SELECT * FROM session_stats;
CREATE OR REPLACE VIEW v_file_io_stats AS SELECT * FROM file_io_stats;
CREATE OR REPLACE VIEW v_blocked_process_reports AS SELECT * FROM blocked_process_reports;
CREATE OR REPLACE VIEW v_deadlocks AS SELECT * FROM deadlocks;
CREATE OR REPLACE VIEW v_dmv_blocking_snapshots AS SELECT * FROM dmv_blocking_snapshots;
CREATE OR REPLACE VIEW v_index_object_stats AS SELECT * FROM index_object_stats;
CREATE OR REPLACE VIEW v_database_size_stats AS SELECT * FROM database_size_stats;
CREATE OR REPLACE VIEW v_tempdb_stats AS SELECT * FROM tempdb_stats;
CREATE OR REPLACE VIEW v_query_snapshots AS SELECT * FROM query_snapshots;
CREATE OR REPLACE VIEW v_database_config AS SELECT * FROM database_config;
CREATE OR REPLACE VIEW v_running_jobs AS SELECT * FROM running_jobs;
CREATE OR REPLACE VIEW v_server_config AS SELECT * FROM server_config;
CREATE OR REPLACE VIEW v_database_scoped_config AS SELECT * FROM database_scoped_config;
CREATE OR REPLACE VIEW v_trace_flags AS SELECT * FROM trace_flags;
CREATE OR REPLACE VIEW v_collection_log AS SELECT * FROM collection_log;
CREATE OR REPLACE VIEW v_memory_clerks AS SELECT * FROM memory_clerks;
CREATE OR REPLACE VIEW v_memory_pressure_events AS SELECT * FROM memory_pressure_events;
CREATE OR REPLACE VIEW v_latch_stats AS SELECT * FROM latch_stats;
CREATE OR REPLACE VIEW v_spinlock_stats AS SELECT * FROM spinlock_stats;
CREATE OR REPLACE VIEW v_cpu_scheduler_stats AS SELECT * FROM cpu_scheduler_stats;
CREATE OR REPLACE VIEW v_plan_cache_stats AS SELECT * FROM plan_cache_stats;
CREATE OR REPLACE VIEW v_session_summary_stats AS SELECT * FROM session_summary_stats;
CREATE OR REPLACE VIEW v_system_health_events AS SELECT * FROM system_health_events;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (14, 'refresh-passthrough-views', now()::timestamp);
-- ===BATCH=== V15 index-metadata-columns

ALTER TABLE index_object_stats ADD COLUMN IF NOT EXISTS key_columns text;
ALTER TABLE index_object_stats ADD COLUMN IF NOT EXISTS included_columns text;
ALTER TABLE index_object_stats ADD COLUMN IF NOT EXISTS filter_definition text;
ALTER TABLE index_object_stats ADD COLUMN IF NOT EXISTS is_unique_constraint boolean;
ALTER TABLE index_object_stats ADD COLUMN IF NOT EXISTS is_foreign_key boolean;
ALTER TABLE index_object_stats ADD COLUMN IF NOT EXISTS is_foreign_key_reference boolean;
ALTER TABLE index_object_stats ADD COLUMN IF NOT EXISTS is_disabled boolean;
ALTER TABLE index_object_stats ADD COLUMN IF NOT EXISTS data_compression_desc text;
ALTER TABLE index_object_stats ADD COLUMN IF NOT EXISTS optimize_for_sequential_key boolean;
ALTER TABLE index_object_stats ADD COLUMN IF NOT EXISTS fill_factor smallint;
ALTER TABLE index_object_stats ADD COLUMN IF NOT EXISTS is_padded boolean;
ALTER TABLE index_object_stats ADD COLUMN IF NOT EXISTS allow_page_locks boolean;
ALTER TABLE index_object_stats ADD COLUMN IF NOT EXISTS allow_row_locks boolean;
ALTER TABLE index_object_stats ADD COLUMN IF NOT EXISTS is_indexed_view boolean;

CREATE OR REPLACE VIEW v_index_object_stats AS SELECT * FROM index_object_stats;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (15, 'index-metadata-columns', now()::timestamp);
-- ===BATCH=== V16 server-utc-offset

ALTER TABLE server_properties ADD COLUMN IF NOT EXISTS utc_offset_minutes integer;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (16, 'server-utc-offset', now()::timestamp);
-- ===BATCH=== V17 config-control-plane

/* V17: store<->service control plane (Stage 1). EVERY object is schema-qualified config.* —
   the migrate session's search_path resolves bare names to collect (wrong schema/ACL). */

/* --- A. Config plane: the Viewer writes desired state, the service reads + honors it. --- */

/* 1. config_monitored_servers — the desired-state twin of the collect.servers observed registry.
      server_id = ServerIdHelper.GetDeterministicHashCode(BuildStorageName(host,database,ro)), the
      SAME identity the collectors stamp, so it JOINs collected data. is_enabled drives collection;
      the connection fields reconstruct a MonitoredServer for the service's connect path. */
CREATE TABLE IF NOT EXISTS config.config_monitored_servers (
    server_id integer NOT NULL PRIMARY KEY,
    name text NOT NULL,
    host text NOT NULL,
    database text,
    auth text NOT NULL DEFAULT 'integrated',
    username text,
    encrypted_password text,
    encrypt_mode text NOT NULL DEFAULT 'Mandatory',
    trust_server_certificate boolean NOT NULL DEFAULT FALSE,
    read_only_intent boolean NOT NULL DEFAULT FALSE,
    multi_subnet_failover boolean NOT NULL DEFAULT FALSE,
    excluded_databases text[] NOT NULL DEFAULT '{}'::text[],
    monthly_cost_usd numeric NOT NULL DEFAULT 0,
    capture_plans boolean,
    is_enabled boolean NOT NULL DEFAULT TRUE,
    created_at timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
    modified_at timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC')
);

/* 2. config_alert_settings — single row (id=1), one column per AlertsConfig field + the analysis
      cadence knobs (analysis_enabled / interval / notifications_enabled / notify_severity). */
CREATE TABLE IF NOT EXISTS config.config_alert_settings (
    id smallint NOT NULL PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    enabled boolean NOT NULL DEFAULT TRUE,
    cpu_enabled boolean NOT NULL DEFAULT TRUE,
    cpu_threshold_percent integer NOT NULL DEFAULT 80,
    cpu_mode text NOT NULL DEFAULT 'total',
    blocking_enabled boolean NOT NULL DEFAULT TRUE,
    blocking_count_threshold integer NOT NULL DEFAULT 1,
    deadlock_enabled boolean NOT NULL DEFAULT TRUE,
    deadlock_count_threshold integer NOT NULL DEFAULT 1,
    poison_wait_enabled boolean NOT NULL DEFAULT TRUE,
    poison_wait_threshold_ms integer NOT NULL DEFAULT 500,
    long_running_query_enabled boolean NOT NULL DEFAULT TRUE,
    long_running_query_threshold_minutes integer NOT NULL DEFAULT 30,
    tempdb_space_enabled boolean NOT NULL DEFAULT TRUE,
    tempdb_space_threshold_percent integer NOT NULL DEFAULT 80,
    low_disk_enabled boolean NOT NULL DEFAULT TRUE,
    low_disk_threshold_percent integer NOT NULL DEFAULT 10,
    low_disk_threshold_gb integer NOT NULL DEFAULT 5,
    long_running_job_enabled boolean NOT NULL DEFAULT TRUE,
    long_running_job_multiplier integer NOT NULL DEFAULT 3,
    failed_job_enabled boolean NOT NULL DEFAULT TRUE,
    failed_job_lookback_minutes integer NOT NULL DEFAULT 60,
    cooldown_minutes integer NOT NULL DEFAULT 5,
    excluded_databases text[] NOT NULL DEFAULT '{}'::text[],
    analysis_enabled boolean NOT NULL DEFAULT TRUE,
    analysis_interval_minutes integer NOT NULL DEFAULT 30,
    analysis_notifications_enabled boolean NOT NULL DEFAULT TRUE,
    analysis_notify_severity double precision NOT NULL DEFAULT 1.5,
    modified_at timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC')
);

/* 3. config_notification — single row: SMTP + webhook delivery. Non-secret fields plus the SMTP
      DPAPI blob (smtp_encrypted_password); webhook URLs/proxies carry as darling.json holds them. */
CREATE TABLE IF NOT EXISTS config.config_notification (
    id smallint NOT NULL PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    smtp_host text NOT NULL DEFAULT '',
    smtp_port integer NOT NULL DEFAULT 587,
    smtp_use_ssl boolean NOT NULL DEFAULT TRUE,
    smtp_username text,
    smtp_encrypted_password text,
    smtp_from_address text NOT NULL DEFAULT '',
    smtp_recipients text NOT NULL DEFAULT '',
    email_cooldown_minutes integer NOT NULL DEFAULT 15,
    teams_url text NOT NULL DEFAULT '',
    teams_proxy text NOT NULL DEFAULT '',
    slack_url text NOT NULL DEFAULT '',
    slack_proxy text NOT NULL DEFAULT '',
    modified_at timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC')
);

/* 4. config_collector_schedules — SPARSE per-collector overrides layered on CollectorScheduleDefaults.
      Absent row / NULL column = code default; server_id NULL = fleet-wide. A PRIMARY KEY cannot span a
      nullable server_id, so two partial-unique indexes enforce one fleet-wide row + one per-server row
      per collector. */
CREATE TABLE IF NOT EXISTS config.config_collector_schedules (
    server_id integer,
    collector_name text NOT NULL,
    frequency_minutes integer CHECK (frequency_minutes >= 0),
    retention_days integer CHECK (retention_days >= 1),
    enabled boolean NOT NULL DEFAULT TRUE
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_config_collector_schedules_fleet
    ON config.config_collector_schedules (collector_name) WHERE server_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_config_collector_schedules_server
    ON config.config_collector_schedules (server_id, collector_name) WHERE server_id IS NOT NULL;

/* 5. config_service — single row: the service-wide flags + the config_version reload beacon. */
CREATE TABLE IF NOT EXISTS config.config_service (
    id smallint NOT NULL PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    paused boolean NOT NULL DEFAULT FALSE,
    capture_plans boolean NOT NULL DEFAULT TRUE,
    mcp_enabled boolean NOT NULL DEFAULT FALSE,
    mcp_port integer NOT NULL DEFAULT 5152,
    config_version bigint NOT NULL DEFAULT 0,
    updated_at timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
    updated_by text
);

/* --- B. Command plane: the Viewer enqueues, the service (Stage 2) claims/executes/reports. --- */

/* 6. config_command — the imperative queue. GENERATED ALWAYS AS IDENTITY (a natural queue key that
      needs no sequence USAGE grant for admin INSERTs, unlike serial). */
CREATE TABLE IF NOT EXISTS config.config_command (
    command_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
    requested_by text,
    command_type text NOT NULL,
    target_server_id integer,
    args_json jsonb,
    status text NOT NULL DEFAULT 'pending',
    claimed_at timestamp,
    completed_at timestamp,
    result_status text,
    result_json jsonb,
    service_instance text
);
CREATE INDEX IF NOT EXISTS idx_config_command_status ON config.config_command (status);

/* --- C. The config_version reload beacon (bump triggers). --- */

/* Statement-level bump on the four desired-state tables: any write increments the beacon so the
   Viewer can never forget to signal. Targets config_service by qualified name (SECURITY INVOKER —
   both writers, the owner during seed and admin via the Viewer, hold UPDATE on config_service). */
CREATE OR REPLACE FUNCTION config.config_bump_version() RETURNS trigger
LANGUAGE plpgsql AS $bump$
BEGIN
    UPDATE config.config_service
       SET config_version = config_version + 1,
           updated_at = (now() AT TIME ZONE 'UTC')
     WHERE id = 1;
    RETURN NULL;
END;
$bump$;

/* Direct writes to config_service (pause/capture/mcp) self-bump the beacon without recursion: the
   BEFORE-UPDATE trigger increments NEW.config_version only when the writer did not already change it
   (so the config_bump_version UPDATE above, which sets config_version explicitly, is not doubled). */
CREATE OR REPLACE FUNCTION config.config_service_bump() RETURNS trigger
LANGUAGE plpgsql AS $svc$
BEGIN
    IF NEW.config_version = OLD.config_version THEN
        NEW.config_version := OLD.config_version + 1;
    END IF;
    NEW.updated_at := (now() AT TIME ZONE 'UTC');
    RETURN NEW;
END;
$svc$;

DROP TRIGGER IF EXISTS trg_bump_monitored_servers ON config.config_monitored_servers;
CREATE TRIGGER trg_bump_monitored_servers
    AFTER INSERT OR UPDATE OR DELETE ON config.config_monitored_servers
    FOR EACH STATEMENT EXECUTE FUNCTION config.config_bump_version();

DROP TRIGGER IF EXISTS trg_bump_alert_settings ON config.config_alert_settings;
CREATE TRIGGER trg_bump_alert_settings
    AFTER INSERT OR UPDATE OR DELETE ON config.config_alert_settings
    FOR EACH STATEMENT EXECUTE FUNCTION config.config_bump_version();

DROP TRIGGER IF EXISTS trg_bump_notification ON config.config_notification;
CREATE TRIGGER trg_bump_notification
    AFTER INSERT OR UPDATE OR DELETE ON config.config_notification
    FOR EACH STATEMENT EXECUTE FUNCTION config.config_bump_version();

DROP TRIGGER IF EXISTS trg_bump_collector_schedules ON config.config_collector_schedules;
CREATE TRIGGER trg_bump_collector_schedules
    AFTER INSERT OR UPDATE OR DELETE ON config.config_collector_schedules
    FOR EACH STATEMENT EXECUTE FUNCTION config.config_bump_version();

DROP TRIGGER IF EXISTS trg_service_self_bump ON config.config_service;
CREATE TRIGGER trg_service_self_bump
    BEFORE UPDATE ON config.config_service
    FOR EACH ROW EXECUTE FUNCTION config.config_service_bump();
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (17, 'config-control-plane', now()::timestamp);
-- ===BATCH=== V18 alert-delivery-mode

ALTER TABLE config.config_alert_settings ADD COLUMN IF NOT EXISTS delivery_mode text NOT NULL DEFAULT 'Summary';
ALTER TABLE config.config_alert_settings ADD COLUMN IF NOT EXISTS per_event_max integer NOT NULL DEFAULT 5;
ALTER TABLE config.config_monitored_servers ADD COLUMN IF NOT EXISTS alert_delivery_mode_override text;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (18, 'alert-delivery-mode', now()::timestamp);
-- ===BATCH=== V19 analysis-state-marker

CREATE TABLE IF NOT EXISTS collect.analysis_state (
    server_id integer NOT NULL PRIMARY KEY,
    insufficient_data boolean NOT NULL DEFAULT FALSE,
    message text,
    analysis_time timestamp NOT NULL
);
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (19, 'analysis-state-marker', now()::timestamp);
-- ===BATCH=== V20 alert-tuning-knobs

ALTER TABLE config.config_alert_settings ADD COLUMN IF NOT EXISTS long_running_query_max_results integer NOT NULL DEFAULT 5;
ALTER TABLE config.config_alert_settings ADD COLUMN IF NOT EXISTS long_running_query_exclude_sp_server_diagnostics boolean NOT NULL DEFAULT TRUE;
ALTER TABLE config.config_alert_settings ADD COLUMN IF NOT EXISTS long_running_query_exclude_wait_for boolean NOT NULL DEFAULT TRUE;
ALTER TABLE config.config_alert_settings ADD COLUMN IF NOT EXISTS long_running_query_exclude_backups boolean NOT NULL DEFAULT TRUE;
ALTER TABLE config.config_alert_settings ADD COLUMN IF NOT EXISTS long_running_query_exclude_misc_waits boolean NOT NULL DEFAULT TRUE;
ALTER TABLE config.config_alert_settings ADD COLUMN IF NOT EXISTS long_running_query_exclude_cdc boolean NOT NULL DEFAULT TRUE;
ALTER TABLE config.config_alert_settings ADD COLUMN IF NOT EXISTS notify_connection_changes boolean NOT NULL DEFAULT TRUE;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (20, 'alert-tuning-knobs', now()::timestamp);
-- ===BATCH=== V21 default-trace-events-collector

CREATE TABLE IF NOT EXISTS collect.default_trace_events (
    default_trace_event_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    event_time timestamp,
    event_name text,
    event_class integer,
    spid integer,
    database_name text,
    database_id integer,
    login_name text,
    host_name text,
    application_name text,
    object_name text,
    filename text,
    integer_data bigint,
    integer_data_2 bigint,
    text_data text,
    session_login_name text,
    error_number integer,
    severity integer,
    state integer,
    event_sequence bigint,
    duration_us bigint,
    end_time timestamp
);

CREATE INDEX IF NOT EXISTS idx_default_trace_events_time ON collect.default_trace_events(server_id, collection_time);
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (21, 'default-trace-events-collector', now()::timestamp);
-- ===BATCH=== V22 index-object-stats-latest-index

CREATE INDEX IF NOT EXISTS idx_index_object_stats_latest ON collect.index_object_stats (server_id, database_id, object_id, index_id, collection_time DESC);
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (22, 'index-object-stats-latest-index', now()::timestamp);
-- ===BATCH=== V23 collection-log-hypertable

/* V23: best-effort UPGRADE fast-path that converts collect.collection_log to a TimescaleDB hypertable + compresses
   it, mirroring the collector hypertables. GUARDED on the extension (plain PostgreSQL skips it, keeping the table a
   heap with batched-DELETE retention) and wrapped in EXCEPTION WHEN OTHERS so it can NEVER abort the startup-critical
   migration. The AUTHORITATIVE conversion is TimescaleSupport.EnsureCollectionLogHypertableAsync at runtime (after
   CREATE EXTENSION), which is the proven-live path and self-heals a fresh store this guard skipped. collection_log is
   NOT in the collector catalog, so the runtime catalog loops never touch it. */
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'timescaledb') THEN
        PERFORM create_hypertable('collect.collection_log', by_range('collection_time', INTERVAL '1 days'), if_not_exists => true, migrate_data => true);
        ALTER TABLE collect.collection_log SET (timescaledb.compress, timescaledb.compress_segmentby = 'server_id');
        PERFORM add_compression_policy('collect.collection_log', compress_after => INTERVAL '1 days', if_not_exists => true);
    END IF;
EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'V23: deferred collection_log hypertable conversion to the runtime path (%): %', SQLSTATE, SQLERRM;
END
$$;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (23, 'collection-log-hypertable', now()::timestamp);
-- ===BATCH=== V24 job-history-collector

CREATE TABLE IF NOT EXISTS collect.job_history (
    job_history_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    instance_id bigint,
    job_id text,
    job_name text,
    job_enabled boolean,
    category_name text,
    step_id integer,
    step_name text,
    run_status integer,
    run_status_desc text,
    run_datetime timestamp,
    run_duration_seconds bigint,
    retries_attempted integer,
    message text
);

CREATE INDEX IF NOT EXISTS idx_job_history_time ON collect.job_history(server_id, collection_time);
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (24, 'job-history-collector', now()::timestamp);
-- ===BATCH=== V25 agent-status-collector

CREATE TABLE IF NOT EXISTS collect.agent_status (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    agent_running boolean,
    agent_status_desc text,
    agent_startup_desc text,
    next_scheduled_run timestamp
);

CREATE INDEX IF NOT EXISTS idx_agent_status_time ON collect.agent_status(server_id, collection_time);
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (25, 'agent-status-collector', now()::timestamp);
-- ===BATCH=== V26 generic-webhook-channel

ALTER TABLE config.config_notification ADD COLUMN IF NOT EXISTS generic_url text NOT NULL DEFAULT '';
ALTER TABLE config.config_notification ADD COLUMN IF NOT EXISTS generic_headers text NOT NULL DEFAULT '';
ALTER TABLE config.config_notification ADD COLUMN IF NOT EXISTS generic_body_template text NOT NULL DEFAULT '';
ALTER TABLE config.config_notification ADD COLUMN IF NOT EXISTS generic_proxy text NOT NULL DEFAULT '';
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (26, 'generic-webhook-channel', now()::timestamp);
-- ===BATCH=== V27 deadlocks-database-name

ALTER TABLE deadlocks ADD COLUMN IF NOT EXISTS database_name text;
CREATE OR REPLACE VIEW v_deadlocks AS SELECT * FROM deadlocks;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (27, 'deadlocks-database-name', now()::timestamp);
-- ===BATCH=== V28 query-store-replica-role

ALTER TABLE query_store_stats ADD COLUMN IF NOT EXISTS replica_role text;
CREATE OR REPLACE VIEW v_query_store_stats AS SELECT * FROM query_store_stats;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (28, 'query-store-replica-role', now()::timestamp);
-- ===BATCH=== V29 long-query-completions-collector

CREATE TABLE IF NOT EXISTS collect.long_query_completions (
    long_query_completion_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    event_time timestamp,
    event_type text,
    database_id integer,
    database_name text,
    session_id integer,
    client_app_name text,
    client_pid integer,
    nt_username text,
    server_principal_name text,
    query_hash text,
    event_sequence bigint,
    duration_microseconds bigint,
    cpu_time_microseconds bigint,
    physical_reads bigint,
    logical_reads bigint,
    writes bigint,
    row_count bigint,
    result text,
    statement_text text,
    object_name text
);

CREATE INDEX IF NOT EXISTS idx_long_query_completions_time ON collect.long_query_completions(server_id, collection_time);
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (29, 'long-query-completions-collector', now()::timestamp);
-- ===BATCH=== V30 web-dashboard-config

ALTER TABLE config.config_service ADD COLUMN IF NOT EXISTS web_enabled boolean NOT NULL DEFAULT FALSE;
ALTER TABLE config.config_service ADD COLUMN IF NOT EXISTS web_port integer NOT NULL DEFAULT 5153;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (30, 'web-dashboard-config', now()::timestamp);
-- ===BATCH=== V31 custom-views-table

CREATE TABLE IF NOT EXISTS config.custom_views (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    definition jsonb NOT NULL,
    description text,
    version integer NOT NULL DEFAULT 1,
    created_at timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
    updated_at timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
    updated_by text
);
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (31, 'custom-views-table', now()::timestamp);
-- ===BATCH=== V32 server-tags

CREATE TABLE IF NOT EXISTS config.server_tags (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    parent_id integer REFERENCES config.server_tags(id) ON DELETE CASCADE,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL DEFAULT (now() AT TIME ZONE 'UTC')
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_server_tags_parent_name
    ON config.server_tags (COALESCE(parent_id, 0), lower(name));

CREATE TABLE IF NOT EXISTS config.server_tag_map (
    server_id integer NOT NULL,
    tag_id integer NOT NULL REFERENCES config.server_tags(id) ON DELETE CASCADE,
    PRIMARY KEY (server_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_server_tag_map_tag
    ON config.server_tag_map (tag_id);
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (32, 'server-tags', now()::timestamp);
-- ===BATCH=== V33 connection-alert-refire

ALTER TABLE config.config_alert_settings
    ADD COLUMN IF NOT EXISTS notify_connection_down_at_startup boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS connection_refire_minutes integer NOT NULL DEFAULT 0;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (33, 'connection-alert-refire', now()::timestamp);
-- ===BATCH=== V34 availability-group-collectors

CREATE TABLE IF NOT EXISTS collect.ag_replica_states (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    ag_name text,
    replica_server_name text,
    role_desc text,
    operational_state_desc text,
    connected_state_desc text,
    recovery_health_desc text,
    synchronization_health_desc text,
    availability_mode_desc text,
    failover_mode_desc text,
    endpoint_url text
);

CREATE INDEX IF NOT EXISTS idx_ag_replica_states_time ON collect.ag_replica_states(server_id, collection_time);

CREATE TABLE IF NOT EXISTS collect.ag_database_replica_states (
    collection_id bigint NOT NULL,
    collection_time timestamp NOT NULL,
    server_id integer NOT NULL,
    server_name text NOT NULL,
    ag_name text,
    database_name text,
    replica_server_name text,
    is_local boolean,
    synchronization_state_desc text,
    last_hardened_lsn text,
    last_commit_lsn text,
    log_send_queue_size bigint,
    redo_queue_size bigint,
    log_send_rate bigint,
    redo_rate bigint,
    is_suspended boolean,
    suspend_reason_desc text,
    availability_mode_desc text,
    secondary_lag_seconds bigint
);

CREATE INDEX IF NOT EXISTS idx_ag_database_replica_states_time ON collect.ag_database_replica_states(server_id, collection_time);
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (34, 'availability-group-collectors', now()::timestamp);
-- ===BATCH=== V35 availability-group-alerts

ALTER TABLE config.config_alert_settings
    ADD COLUMN IF NOT EXISTS notify_ag_health boolean NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS ag_lag_alert_seconds integer NOT NULL DEFAULT 300,
    ADD COLUMN IF NOT EXISTS ag_redo_queue_alert_kb bigint NOT NULL DEFAULT 0;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (35, 'availability-group-alerts', now()::timestamp);
-- ===BATCH=== V36 ag-latency-columns

ALTER TABLE collect.ag_database_replica_states
    ADD COLUMN IF NOT EXISTS last_commit_time timestamp,
    ADD COLUMN IF NOT EXISTS last_hardened_time timestamp,
    ADD COLUMN IF NOT EXISTS last_redone_time timestamp,
    ADD COLUMN IF NOT EXISTS last_received_time timestamp,
    ADD COLUMN IF NOT EXISTS est_redo_completion_time_min double precision,
    ADD COLUMN IF NOT EXISTS est_send_drain_time_min double precision;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (36, 'ag-latency-columns', now()::timestamp);
-- ===BATCH=== V37 ag-local-replica-and-disconnect-refire

ALTER TABLE collect.ag_replica_states
    ADD COLUMN IF NOT EXISTS is_local boolean;

ALTER TABLE config.config_alert_settings
    ADD COLUMN IF NOT EXISTS ag_disconnect_refire_minutes integer NOT NULL DEFAULT 0;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (37, 'ag-local-replica-and-disconnect-refire', now()::timestamp);
-- ===BATCH=== V38 query-payload-dimensions
/* V38: hash-keyed dimension tables for query_stats / procedure_stats payloads (#1767).
   query_text/query_plan_xml stored inline per row were 94% of a 250 GB field store;
   a measured 1-hour window held 3,166 MB of payload across 23 MB of distinct content.
   ZERO-REWRITE: the inline columns stay, new rows leave them NULL, readers coalesce,
   and raw retention ages the inline copies out on its own. */

CREATE TABLE IF NOT EXISTS query_text_dim (
    digest bytea NOT NULL PRIMARY KEY,
    query_text text NOT NULL,
    last_seen timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_query_text_dim_last_seen ON query_text_dim(last_seen);

CREATE TABLE IF NOT EXISTS query_plan_dim (
    digest bytea NOT NULL PRIMARY KEY,
    query_plan_xml text NOT NULL,
    last_seen timestamp NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_query_plan_dim_last_seen ON query_plan_dim(last_seen);

ALTER TABLE query_stats ADD COLUMN IF NOT EXISTS query_text_digest bytea;
ALTER TABLE query_stats ADD COLUMN IF NOT EXISTS query_plan_digest bytea;
ALTER TABLE procedure_stats ADD COLUMN IF NOT EXISTS query_plan_digest bytea;

/* v_query_stats resolves each row's payload: the inline column for rows written before
   the dimension tables existed, the dimension row for every row written since (#1767).
   Column list generated from the collector definition so it can never go stale. */
CREATE OR REPLACE VIEW v_query_stats AS
SELECT
    f.collection_id,
    f.collection_time,
    f.server_id,
    f.server_name,
    f.database_name,
    f.query_hash,
    f.query_plan_hash,
    f.creation_time,
    f.last_execution_time,
    f.execution_count,
    f.total_worker_time,
    f.total_elapsed_time,
    f.total_logical_reads,
    f.total_logical_writes,
    f.total_physical_reads,
    f.total_clr_time,
    f.total_rows,
    f.total_spills,
    f.min_worker_time,
    f.max_worker_time,
    f.min_elapsed_time,
    f.max_elapsed_time,
    f.min_physical_reads,
    f.max_physical_reads,
    f.min_rows,
    f.max_rows,
    f.min_dop,
    f.max_dop,
    f.min_grant_kb,
    f.max_grant_kb,
    f.min_used_grant_kb,
    f.max_used_grant_kb,
    f.min_ideal_grant_kb,
    f.max_ideal_grant_kb,
    f.min_reserved_threads,
    f.max_reserved_threads,
    f.min_used_threads,
    f.max_used_threads,
    f.min_spills,
    f.max_spills,
    COALESCE(f.query_text, qtd.query_text) AS query_text,
    COALESCE(f.query_plan_xml, qpd.query_plan_xml) AS query_plan_xml,
    f.sql_handle,
    f.plan_handle,
    f.delta_execution_count,
    f.delta_worker_time,
    f.delta_elapsed_time,
    f.delta_logical_reads,
    f.delta_logical_writes,
    f.delta_physical_reads,
    f.delta_rows,
    f.delta_spills,
    f.plan_generation_num,
    f.sample_interval_seconds,
    f.query_text_digest,
    f.query_plan_digest
FROM query_stats AS f
LEFT JOIN query_text_dim AS qtd ON qtd.digest = f.query_text_digest
LEFT JOIN query_plan_dim AS qpd ON qpd.digest = f.query_plan_digest
;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (38, 'query-payload-dimensions', now()::timestamp);
-- ===BATCH=== V39 dim-feeding-fact-floor-indexes

CREATE INDEX IF NOT EXISTS ix_query_stats_digest_floor
    ON query_stats (collection_time)
    WHERE query_text_digest IS NOT NULL OR query_plan_digest IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_procedure_stats_digest_floor
    ON procedure_stats (collection_time)
    WHERE query_plan_digest IS NOT NULL;
INSERT INTO darling_schema_version (version, name, applied_at) VALUES (39, 'dim-feeding-fact-floor-indexes', now()::timestamp);
