using System.Text;
using PerformanceMonitor.Darling.Storage;

var sb = new StringBuilder();
sb.Append("-- Migration ladder as RESOLVED by the release this fixture is named for — every rung's\n");
sb.Append("-- SQL frozen as that era's code (including its generators) emitted it, plus the same\n");
sb.Append("-- version-table DDL and stamps MigrateLockedAsync writes. Generated by tools/generate-\n");
sb.Append("-- ladder-fixture; regenerate at each release cut from the release tag. DO NOT HAND-EDIT.\n");
sb.Append("-- ===BATCH=== bootstrap\n");
sb.Append("SET search_path = collect, config, public;\n");
sb.Append("CREATE TABLE IF NOT EXISTS darling_schema_version (\n    version integer NOT NULL PRIMARY KEY,\n    name text NOT NULL,\n    applied_at timestamp NOT NULL\n);\n");

foreach (var m in PgMigrations.Scripts)
{
    sb.Append("-- ===BATCH=== V").Append(m.Version).Append(' ').Append(m.Name).Append('\n');
    sb.Append(m.Sql.TrimEnd()).Append('\n');
    sb.Append("INSERT INTO darling_schema_version (version, name, applied_at) VALUES (")
      .Append(m.Version).Append(", '").Append(m.Name.Replace("'", "''")).Append("', now()::timestamp);\n");
}

File.WriteAllText(args[0], sb.ToString());
Console.WriteLine($"wrote {args[0]}: {PgMigrations.Scripts.Count} rungs, top V{PgMigrations.Scripts[^1].Version}");
